name: santorini_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.5
  animated_splash: ^1.0.0
  http: ^0.12.0+1
  json_serializable: ^3.3.0
  flutter_sliding_up_panel: ^1.1.0+1
  carousel_slider: ^2.3.1
  panorama: ^0.3.1
  rate_my_app: ^0.6.0+2
  country_icons: ^1.1.1
  url_launcher: 5.5.0
  external_app_launcher: ^0.0.1
  share: ^0.6.5+4
  favorite_button: ^0.0.3
  path_provider: ^1.6.27
  scroll_snap_list: ^0.6.0
  video_player: ^1.0.1
  chewie: ^0.12.2
  sliding_up_panel: ^1.0.2
  image_picker: ^0.6.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_bloc: ^2.1.1
  equatable:
  rxdart: ^0.22.0
  quick_feedback:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/main.jpg
    - images/normalMarker.png
    - images/selectedMarker.png
    - images/museum.png
    - images/akrotirithera.jpg
    - images/volcano.png
    - images/church.png
    - images/archeological.png
    - images/path.png
    - images/mapmarker.png
    - images/santorini_logo.png
    - locations/locations.json
    - locations/locations2.json
    - locations/monument-list.json
    - images/marker1.png
    - images/pins/archaelogical.png
    - images/pins/churches.png
    - images/pins/laography.png
    - images/pins/museums.png
    - images/pins/paths.png
    - images/pins/volcanos.png
    - images/monuments/
    - images/monuments/orthodox_ypapanti/gallery/AERIAL PHOTO BB0 SMALL.jpg
    - images/monuments/akrotiri/gallery/a1-min.jpg
    - images/monuments/maritime_museum/gallery/DSC05616 SMALL.jpg
    - images/monuments/new_kameni/gallery/C0460 CUT B SMALL.jpg
    - images/monuments/palaia_kameni/gallery/C0473 A0 SMALL-min.jpg
    - images/monuments/palaiochristianiki/gallery/DSC05062 SMALL-min.jpg
    - images/monuments/panagia_episkopi/gallery/pan epi09407 CUT SMALL.jpg
    - images/monuments/prehistoric_museum/gallery/EXTERIOR 01.jpg
    - images/monuments/tomato/gallery/DSC05075 SMALL.jpg
    - images/monuments/walking_path_megaloxori_pirgos_emporio/gallery/bb0.jpg
    - images/monuments/walking_path_oia/gallery/Megalochori01.jpg
    - images/logo.png
    - images/logo_white.png
    - images/iconcontact.png
    - images/santorini1.png
    - images/santorini2.png
    - images/santorini3.png
    - images/santorini4.png
    - images/all1.png
    - images/stars.png
    - images/instagram.png
    - images/twitter.png
    - video/akrotiri/akrotitri.mp4
    - images/panorama/test.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
